<%@ Page Title="" Language="C#" MasterPageFile="~/Paginas/Site1.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Vistas.Paginas.Carrito" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="resto" runat="server">
    <br />
<br />
<br />
     <asp:GridView ID="grvCarrito" runat="server" AutoGenerateColumns="False" OnRowDataBound="grvCarrito_RowDataBound" OnRowCommand="grvCarrito_RowCommand" AutoGenerateDeleteButton="True" OnRowDeleting="grvCarrito_RowDeleting" CssClass="table table-striped" Height="635px" Width="730px">
    <Columns>
        <asp:TemplateField HeaderText="Producto">
            <ItemTemplate>
                <asp:Image ID="imgProducto" runat="server" Height="113px" Width="134px" CssClass="img-fluid" ImageUrl='<%# Eval("Producto") %>' />
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Descripcion">
            <ItemTemplate>
                <asp:Label ID="lblDescripcion" runat="server" Text='<%# Eval("Descripcion") %>' CssClass="fw-bold"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Precio">
            <ItemTemplate>
                <asp:Label ID="lblPrecio" runat="server" Text='<%# Eval("Precio") %>' CssClass="text-success"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Cantidad">
            <ItemTemplate>
                <div class="d-flex align-items-center">
                    <asp:LinkButton ID="btnDisminuir" runat="server" CommandName="disminuirCantidad" CommandArgument='<%# Container.DataItemIndex %>' CssClass="btn btn-outline-primary border-0">
                        <i class="bi bi-dash-circle"></i>
                    </asp:LinkButton>
                    <asp:TextBox ID="txtCantidad" runat="server" CssClass="form-control" />
                    <asp:LinkButton ID="btnAumentar" runat="server" CommandName="aumentarCantidad" CommandArgument='<%# Container.DataItemIndex %>' CssClass="btn btn-outline-primary border-0">
                    <i class="bi bi-plus-circle"></i>
                    </asp:LinkButton>
                </div>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Subtotal">
            <ItemTemplate>
                <asp:Label ID="lblSubtotal" runat="server"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
</asp:GridView>
            <div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <asp:Button ID="btnVaciar" runat="server" CssClass="btn btn-danger" OnClick="btnVaciar_Click" Text="VACIAR CARRITO" Width="164px" Height="32px" />
            <asp:Label ID="lblSinArticulos" runat="server" Text="No ha seleccionado ningun articulo" Visible="False"></asp:Label>
&nbsp;<p class="mt-3">
                <asp:Label ID="lblTextTotal" runat="server" CssClass="fw-bold" Text="Total de la Venta: "></asp:Label>
                <asp:Label ID="lblTotalVenta" runat="server" CssClass="fw-bold text-success"></asp:Label>
            </p>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <p class="fw-bold">
                <asp:Label ID="lblMensaje" runat="server" Text="Por favor, seleccione dónde lo recibirá:"></asp:Label>
            </p>
            <ul class="list-unstyled">
                <asp:RadioButton ID="DomicilioRB" Text="Domicilio" runat="server" Checked="True" GroupName="grupoEnvio" AutoPostBack="True" OnCheckedChanged="RadioButton_CheckedChanged" CssClass="form-check-input" />
                <asp:RadioButton ID="LocalRB" Text="Local" runat="server" GroupName="grupoEnvio" AutoPostBack="True" OnCheckedChanged="RadioButton_CheckedChanged" CssClass="form-check-input" />
                <asp:RadioButton ID="CorreoRB" Text="Correo" runat="server" GroupName="grupoEnvio" AutoPostBack="True" OnCheckedChanged="RadioButton_CheckedChanged" CssClass="form-check-input" />
            </ul>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <asp:Label ID="lblCorreo" runat="server" Text="Puestos de Correo" Visible="false" CssClass="fw-bold"></asp:Label>
            <asp:DropDownList ID="ddlCorreo" runat="server" Visible="false" CssClass="form-select">
                <asp:ListItem Text="Seleccione Puesto de Correo" Value="seleccion" Disabled="true" Selected="true"></asp:ListItem>
                <asp:ListItem Value="Puesto 1">Puesto 1</asp:ListItem>
                <asp:ListItem Value="Puesto 2">Puesto 2</asp:ListItem>
                <asp:ListItem Value="Puesto 3">Puesto 3</asp:ListItem>
                <asp:ListItem Value="Puesto 4">Puesto 4</asp:ListItem>
                <asp:ListItem Value="Puesto 5">Puesto 5</asp:ListItem>
            </asp:DropDownList>
            <div class="col-md-6">
            <asp:Label ID="lblDireccion" runat="server" Text="Dirección:" Visible="False" CssClass="fw-bold"></asp:Label>
            <asp:TextBox ID="txtDireccion" runat="server" CssClass="form-control" MaxLength="30"></asp:TextBox>
            <asp:Label ID="lblError" runat="server" CssClass="text-danger"></asp:Label>
                <br />
                <br />
                <br />
            <asp:Button ID="btnComprar" runat="server" CssClass="btn btn-success" OnClick="btnComprar_Click" Text="COMPRAR" Width="145px" />
            </div>
        </div>
    </div>
</div>

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="PieDePagina" runat="server">
</asp:Content>
